/**
 * Inventory Management System - Reorder Queue & Procurement Recommendations Page
 */
import React, { useEffect, useState, useCallback } from 'react';
import api from '../api';
import {
  Card,
  CardsGrid,
  Button,
  Table,
  TableHead,
  TableRow,
  TableCell,
  Modal,
  useToast,
  formatCurrency,
  formatDate,
  priorityBadge,
  statusBadge,
  loadingSkeleton
} from '../components/UI';
import {
  RotateCcw,
  CheckCircle2,
  DollarSign,
  Package,
  Truck,
  ShoppingCart,
  Clock,
  Sparkles,
  Boxes
} from 'lucide-react';

const Reorders = () => {
  const [reorders, setReorders] = useState([]);
  const [loading, setLoading] = useState(true);
  const { showToast } = useToast();

  // Fulfill Reorder Modal
  const [fulfillModalOpen, setFulfillModalOpen] = useState(false);
  const [selectedReorder, setSelectedReorder] = useState(null);
  const [orderQty, setOrderQty] = useState('');
  const [orderSupplier, setOrderSupplier] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const loadReorders = useCallback(async () => {
    try {
      const res = await api.getReorderSuggestions();
      setReorders(res.data || []);
      setLoading(false);
    } catch (err) {
      console.error('Failed to load reorder suggestions:', err);
      showToast('Failed to calculate reorder queue', 'error');
      setLoading(false);
    }
  }, [showToast]);

  useEffect(() => {
    loadReorders();
    const handleRefresh = () => loadReorders();
    window.addEventListener('ims_refresh', handleRefresh);
    return () => window.removeEventListener('ims_refresh', handleRefresh);
  }, [loadReorders]);

  const handleOpenFulfillModal = (item) => {
    setSelectedReorder(item);
    setOrderQty(String(item.reorderQuantity));
    setOrderSupplier(item.supplier || 'Primary Supplier');
    setFulfillModalOpen(true);
  };

  const handleFulfillOrder = async (e) => {
    e.preventDefault();
    if (!selectedReorder) return;
    const qty = parseFloat(orderQty);
    if (!qty || qty <= 0) {
      showToast('Please enter a valid order quantity', 'warning');
      return;
    }

    setSubmitting(true);
    try {
      await api.restockProduct({
        productId: selectedReorder.productId,
        quantity: qty,
        reason: `PO Replenishment (${orderSupplier})`
      });
      showToast(`Purchase order fulfilled: +${qty} units of ${selectedReorder.productName}`, 'success');
      setFulfillModalOpen(false);
      setSelectedReorder(null);
      loadReorders();
    } catch (err) {
      showToast(err.message || 'Failed to process replenishment order', 'error');
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="reorders-page animate-fade-in">
        <div className="page-header">
          <div className="page-title-group">
            <h1 className="page-title">Reorder Queue & Recommendations</h1>
            <p className="page-subtitle">Calculating inventory replenishment needs...</p>
          </div>
        </div>
        {loadingSkeleton(6, 6)}
      </div>
    );
  }

  const totalReorderUnits = reorders.reduce((acc, r) => acc + (parseFloat(r.reorderQuantity) || 0), 0);
  const totalReorderEstCost = reorders.reduce((acc, r) => acc + (parseFloat(r.estimatedCost) || 0), 0);
  const criticalCount = reorders.filter((r) => r.priority === 'CRITICAL').length;

  return (
    <div className="reorders-page animate-fade-in">
      {/* Page Header */}
      <div className="page-header">
        <div className="page-title-group">
          <h1 className="page-title">Smart Reorder Queue</h1>
          <p className="page-subtitle">
            Dynamic procurement suggestions generated by safety buffer analysis and predicted run rates
          </p>
        </div>
      </div>

      {/* KPI Cards Grid */}
      <CardsGrid cols={3}>
        <Card className="metric-card">
          <div className="metric-info">
            <span className="metric-label">Recommended Reorder Units</span>
            <span className="metric-value font-mono">{totalReorderUnits} Units</span>
            <span className="metric-subtext">Across {reorders.length} inventory products</span>
          </div>
          <div className="metric-icon-wrapper icon-blue">
            <Boxes size={22} />
          </div>
        </Card>

        <Card className="metric-card">
          <div className="metric-info">
            <span className="metric-label">Estimated PO Procurement Cost</span>
            <span className="metric-value font-mono text-primary">
              {formatCurrency(totalReorderEstCost)}
            </span>
            <span className="metric-subtext">Based on current unit prices</span>
          </div>
          <div className="metric-icon-wrapper icon-emerald">
            <DollarSign size={22} />
          </div>
        </Card>

        <Card className="metric-card">
          <div className="metric-info">
            <span className="metric-label">Rush Reorder Orders</span>
            <span className="metric-value font-mono text-danger">
              {criticalCount} Urgent
            </span>
            <span className="metric-subtext">Zero or near-depleted stock</span>
          </div>
          <div className="metric-icon-wrapper icon-rose">
            <Truck size={22} />
          </div>
        </Card>
      </CardsGrid>

      {/* Reorders Table */}
      <Card title="Replenishment Order Schedule" subtitle="Prioritized list of supplier orders required to prevent out-of-stock events">
        {reorders.length === 0 ? (
          <div className="empty-state">
            <div className="empty-icon-wrapper" style={{ background: 'rgba(16, 185, 129, 0.15)', color: 'var(--success-500)' }}>
              <CheckCircle2 size={32} />
            </div>
            <h3 className="empty-title">Procurement queue is empty!</h3>
            <p className="empty-description">
              All inventory levels currently satisfy their 30-day forecast and safety stock parameters.
            </p>
          </div>
        ) : (
          <Table>
            <TableHead>
              <TableRow>
                <TableCell isHeader>Priority</TableCell>
                <TableCell isHeader>Product / SKU</TableCell>
                <TableCell isHeader>Supplier</TableCell>
                <TableCell isHeader>Current Stock</TableCell>
                <TableCell isHeader>Target Buffer</TableCell>
                <TableCell isHeader>Reorder Qty</TableCell>
                <TableCell isHeader>Est. Cost</TableCell>
                <TableCell isHeader style={{ textAlign: 'right' }}>Action</TableCell>
              </TableRow>
            </TableHead>
            <tbody>
              {reorders.map((item) => (
                <TableRow key={item.productId}>
                  <TableCell>
                    {priorityBadge(item.priority)}
                  </TableCell>
                  <TableCell>
                    <div className="font-semibold">{item.productName}</div>
                    <span className="font-mono text-xs text-muted">{item.sku}</span>
                  </TableCell>
                  <TableCell className="text-secondary text-sm">
                    {item.supplier}
                  </TableCell>
                  <TableCell>
                    {statusBadge(item.currentStock, item.minimumStock)}
                  </TableCell>
                  <TableCell>
                    <span className="font-mono text-secondary">
                      {(item.predictedDemand || 0) + (item.safetyStock || 0)} units
                    </span>
                  </TableCell>
                  <TableCell>
                    <span className="font-mono font-bold text-primary" style={{ fontSize: '0.95rem' }}>
                      +{item.reorderQuantity}
                    </span>
                  </TableCell>
                  <TableCell className="font-mono font-semibold">
                    {formatCurrency(item.estimatedCost)}
                  </TableCell>
                  <TableCell style={{ textAlign: 'right' }}>
                    <Button
                      variant={item.priority === 'CRITICAL' ? 'danger' : 'primary'}
                      size="sm"
                      icon={Truck}
                      onClick={() => handleOpenFulfillModal(item)}
                    >
                      Receive PO
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </tbody>
          </Table>
        )}
      </Card>

      {/* Modal: Fulfill Reorder */}
      <Modal
        isOpen={fulfillModalOpen}
        onClose={() => setFulfillModalOpen(false)}
        title={`Receive Supplier Order: ${selectedReorder?.productName}`}
        footer={
          <>
            <Button variant="secondary" onClick={() => setFulfillModalOpen(false)}>
              Cancel
            </Button>
            <Button variant="success" onClick={handleFulfillOrder} loading={submitting}>
              Confirm Stock Receipt
            </Button>
          </>
        }
      >
        <form onSubmit={handleFulfillOrder}>
          <div className="form-group">
            <label className="form-label">Supplier Name</label>
            <input
              type="text"
              className="form-input"
              value={orderSupplier}
              onChange={(e) => setOrderSupplier(e.target.value)}
              required
            />
          </div>

          <div className="form-grid-2">
            <div className="form-group">
              <label className="form-label">Order Quantity (Units) *</label>
              <input
                type="number"
                min="1"
                className="form-input font-mono"
                value={orderQty}
                onChange={(e) => setOrderQty(e.target.value)}
                required
              />
            </div>

            <div className="form-group">
              <label className="form-label">Unit Price ($ USD)</label>
              <input
                type="text"
                className="form-input font-mono"
                disabled
                value={formatCurrency(selectedReorder?.unitPrice || 0)}
              />
            </div>
          </div>

          <div
            style={{
              padding: '0.85rem',
              background: 'var(--bg-subtle)',
              borderRadius: 'var(--radius-md)',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              marginTop: '0.5rem'
            }}
          >
            <span className="text-sm font-semibold">Total PO Expenditure:</span>
            <span className="font-mono font-bold text-primary" style={{ fontSize: '1.1rem' }}>
              {formatCurrency((parseFloat(orderQty) || 0) * (selectedReorder?.unitPrice || 0))}
            </span>
          </div>
        </form>
      </Modal>
    </div>
  );
};

export default Reorders;